stages:
  get_data:
    cmd: python src/get_data.py --output_dir datasets
    deps:
      - src/get_data.py
    outs:
      - datasets/
  preprocess:
    cmd: python src/prepare_data.py --output_dir data/ --dataset datasets/a1_RestaurantReviews_HistoricDump.tsv
    deps:
      - src/prepare_data.py
    outs:
      - data/X.npy
      - data/cv.pkl
      - data/y.npy
