train:
  train_all: false # DO NOT CHANGE, the pipeline will fail if we don't have a test set
  test_size: 0.2
  random_state: 45
  var_smoothing: 1e-07
  priors:      # Can be something like [0.5, 0.5]
